type CardTagString = 'Action'
                    | 'Event'
                    | 'DeathEvent'
                    | 'Option'
                    | 'Eureka'
                    | 'Legacy'
                    | 'Guard'
                    | 'Pillage'
                    | 'Rush'
                    | 'Rent'
                    | 'Fervour'
                    | 'Debt'
                    | 'Income'
                    | 'Growth'

export default CardTagString