export type EventsDomainString = 'deathEvents' | 'enterPlayEvents' | 'playEvents'
export type TargetDomainString = 'self' 
                                | 'enemyLeader' 
                                | 'friendlyLeader' 
                                | 'leftFollower' 
                                | 'rightFollower' 
                                | 'oppositeFollower' 
                                | 'enemyPlayer' 
                                | 'friendlyPlayer' 
                                | 'enemyLeaderTechnique'
                                | 'friendlyLeaderTechnique'
export type TargetsDomainString = TargetDomainString 
                                | 'enemyBoard' 
                                | 'friendlyBoard' 
                                | 'enemyCreations' 
                                | 'friendlyCreations' 
                                | 'enemyHand' 
                                | 'friendlyHand' 
                                | 'enemyDeck' 
                                | 'friendlyDeck' 
                                | 'adjacentFollowers' 
                                | 'neighbouringFollowers'
                                | 'enemyLegacy'
                                | 'friendlyLegacy'