export type EventsDomainString = 'deathEvents' | 'enterPlayEvents' | 'playEvents'
export type TargetDomainString = 'self' | 'enemyLeader' | 'friendlyLeader' | 'leftFollower' | 'rightFollower' | 'oppositeFollower' | 'friendlyPlayer' | 'enemyPlayer'
export type TargetsDomainString = TargetDomainString 
                                | 'enemyBoard' 
                                | 'friendlyBoard' 
                                | 'enemyCreations' 
                                | 'friendlyCreations' 
                                | 'enemyHand' 
                                | 'friendlyHand' 
                                | 'enemyDeck' 
                                | 'friendlyDeck' 
                                | 'adjacentFollowers' 
                                | 'neighbouringFollowers'
                                | 'enemyLegacy'
                                | 'friendlyLegacy'