type EventTypeString = 'death' 
                        | 'play' 
                        | 'action' 
                        | 'optionAction'
                        // | 'eurekaAction'
                        | 'eventAction'
                        | 'deathAction'
                        | 'attack' 
                        | 'damage' 
                        | 'healing' 
                        | 'draw' 
                        | 'enterPlay' 
                        | 'summon' 
                        | 'use' 
                        | 'startOfTurn' 
                        | 'endOfTurn' 
                        | 'spendMoney'
                        | 'accrueDebt'
                        | 'trigger'
                        | 'update'

export default EventTypeString