type TriggerTypeString = 'afterDeath' 
                        | 'startOfTurn' 
                        | 'endOfTurn' 
                        | 'proposedAttack' 
                        | 'beforeAttack' 
                        | 'afterAttack' 
                        | 'beforeDamage' 
                        | 'afterDamage' 
                        | 'beforeHealing'
                        | 'afterHealing'
                        | 'afterOverhealing'
                        | 'beforePlay' 
                        | 'afterPlay' 
                        | 'afterEnterPlay' 
                        | 'beforeAction' 
                        | 'afterAction'
                        | 'beforeOptionAction'
                        | 'afterOptionAction'
                        | 'beforeEventAction' 
                        | 'afterEventAction'
                        | 'beforeDeathAction' 
                        | 'afterDeathAction'
                        // | 'beforeEurekaAction' 
                        // | 'afterEurekaAction'
                        | 'proposedDrawEvent'
                        | 'beforeDraw'
                        | 'onDraw'
                        | 'afterDraw'
                        | 'beforeSpendMoney'
                        | 'afterSpendMoney'
                        | 'beforeAccrueDebt'
                        | 'afterAccrueDebt'
                        | 'auraReset'
                        | 'staticApply'
                        | 'auraEmit0'
                        | 'auraApply0'
                        | 'calculateGlobals'
                        | 'auraEmit1'
                        | 'auraApply1'
                        | 'auraEmit2'
                        | 'auraApply2'
                        | 'applyPassionate'
                        | 'applyInherited'
                        | 'auraEmit3'
                        | 'auraApply3'
                        | 'finishUpdate'
                        | 'afterAuraUpdate'

export default TriggerTypeString                        