type TriggerTypeString = 'afterDeath' 
                        | 'startOfTurn' 
                        | 'endOfTurn' 
                        | 'proposedAttack' 
                        | 'beforeAttack' 
                        | 'afterAttack' 
                        | 'beforeDamage' 
                        | 'afterDamage' 
                        | 'onPlay' 
                        | 'afterPlay' 
                        | 'onSummon' 
                        | 'afterSummon' 
                        | 'beforeSpell' 
                        | 'afterSpell'
                        | 'proposedDrawSequence'
                        | 'beforeDraw'
                        | 'onDraw'
                        | 'afterDraw'

export default TriggerTypeString                        