type TriggerTypeString = 'afterDeath' 
                        | 'startOfTurn' 
                        | 'endOfTurn' 
                        | 'proposedAttack' 
                        | 'beforeAttack' 
                        | 'afterAttack' 
                        | 'beforeDamage' 
                        | 'afterDamage' 
                        | 'beforeHealing'
                        | 'afterHealing'
                        | 'onPlay' 
                        | 'afterPlay' 
                        | 'onEnterPlay' 
                        | 'beforeAction' 
                        | 'afterAction'
                        | 'beforeEventAction' 
                        | 'afterEventAction'
                        | 'beforeDeathAction' 
                        | 'afterDeathAction'
                        | 'proposedDrawEvent'
                        | 'beforeDraw'
                        | 'onDraw'
                        | 'afterDraw'
                        | 'beforeSpendMoney'
                        | 'afterSpendMoney'
                        | 'auraReset'
                        | 'auraEmit1'
                        | 'auraEmit2'
                        | 'auraEmit3'
                        | 'auraApply'

export default TriggerTypeString                        