const CivilDisobedience: DeckObject = {
    id: 'CivilDisobedience',
    name: 'Civil Disobedience',
    class: 'The People',
    leader: 'NelsonMandela',
    passive: 'PeacefulResistance',
    cards: [
        'Collectivisation',
        'Collectivisation',
        'StatueOfLiberty',
        'StatueOfLiberty',
        'Spartacus',
        'Spartacus',
        'RomanSlave',
        'RomanSlave',
        'UnarmedSoviet',
        'UnarmedSoviet',
        'SelmaMarcher',
        'SelmaMarcher',
        'FrenchRevolution',
        'FrenchRevolution',
        'MahatmaGandhi',
        'MahatmaGandhi',
        'Robespierre',
        'Robespierre',
        'SaintJust',
        'SaintJust',
        'LesMiserables',
        'LesMiserables',
        'StonewallRioter',
        'StonewallRioter',
        // 'LudwigII',
        // 'LudwigII',
        'FidelCastro',
        'FidelCastro',
        'EdwardTheBlackPrince',
        'EdwardTheBlackPrince',
        // 'TankMan',
        // 'TankMan',
        // 'Cleon',
        // 'Cleon',
        // 'StormingOfTheBastille',
        // 'StormingOfTheBastille',
        'GeneralStrike1926',
        'GeneralStrike1926',
    ],
    description: `Defeat your foes through non-violent protest in this life-gain deck. Play defensively and build your board and your leader's Health, until you're ready to flip the tables with Spartacus, or renounce pacifism entirely and nuke your opponent.`,
    tips: `- If your opponent is using an aggressive deck, rely on Nelson Mandela's leader technique to keep you alive until you've worn them out - you don't need to play Spartacus as soon as you draw him.
           - Saint-Just and the French Revolution pair well.
           - If you have secured control of the board with your pacifist followers, use Spartacus to go on the offensive.
           - If your leader's Health is high enough, you might instead trigger the Cuban Missile Crisis and win the game by suriving a nuclear exchange.`,
}

export default CivilDisobedience

import DeckObject from '../structs/DeckObject'