const CivilDisobedience: DeckObject = {
    id: 'CivilDisobedience',
    name: 'Civil Disobedience',
    class: 'The People',
    leader: 'NelsonMandela',
    passive: 'PeacefulResistance',
    cards: [
        'Collectivisation',
        'Collectivisation',
        'StatueOfLiberty',
        'StatueOfLiberty',
        'Spartacus',
        'Spartacus',
        'Slave',
        'Slave',
        'UnarmedSoviet',
        'UnarmedSoviet',
        'SelmaMarcher',
        'SelmaMarcher',
        'FrenchRevolution',
        'FrenchRevolution',
        'MahatmaGandhi',
        'MahatmaGandhi',
        'Robespierre',
        'Robespierre',
        'SaintJust',
        'SaintJust',
        'LesMiserables',
        'LesMiserables',
        'StonewallRioter',
        'StonewallRioter',
        'LudwigII',
        'LudwigII',
        'TankMan',
        'TankMan',
        // 'Cleon',
        // 'Cleon',
        // 'StormingOfTheBastille',
        // 'StormingOfTheBastille',
        'GeneralStrike1926',
        'GeneralStrike1926',
    ]
}

export default CivilDisobedience

import DeckObject from '../structs/DeckObject'