const HarshMedicine: DeckObject = {
    id:  'HarshMedicine',
    name: 'Harsh Medicine',
    class: 'Learning',
    leader: 'Hippocrates',
    passive: 'HippocraticOath',
    cards: [
        // 'UniversityOfOxford',
        // 'UniversityOfOxford',
        // 'VenetianPatentStatute',
        // 'VenetianPatentStatute',
        'AlexanderFleming',
        'AlexanderFleming',
        'IsaacNewton',
        'IsaacNewton',
        // 'LibraryOfAlexandria',
        // 'LibraryOfAlexandria',
        'Chemotherapy',
        'Chemotherapy',
        // 'HelenOfTroy',
        // 'HelenOfTroy',
        'Konigstiger',
        'Konigstiger',
        'AlfredNobel',
        'AlfredNobel',
        // 'ThomasBodley',
        // 'ThomasBodley',
        // 'Triage',
        // 'Triage',
        'EdwardTheBlackPrince',
        'EdwardTheBlackPrince',
        'InjuredSkater',
        'InjuredSkater',
        'HenryFord',
        'HenryFord',
        'Robespierre',
        'Robespierre',
        // 'JohnFKennedy',
        // 'JohnFKennedy',
        // 'RansomEOlds',
        // 'RansomEOlds',
        'Theodora',
        'Theodora',
        'ErasmusExchange',
        'ErasmusExchange',
        'JRobertOppenheimer',
        'JRobertOppenheimer',
        'PrimaryEducation',
        'PrimaryEducation',
        'MonasticRetreat',
        'MonasticRetreat',
        'Dolly',
        'Dolly',
    ],
    description: `Defeat your enemy with the power of medicine in this healing-centric deck.`,
    tips: `- Your cards that restore followers to full Health synergise powerfully with Hippocratic Oath - they'll increase the target's max Health by however much Health they were missing.
           - Aim to get Alfred Nobel killed as early as possible, to take advantage of his Legacy effect.
           - Give Dolly the Sheep a Primary Education (and then try returning her to your hand using Theodora or Monastic Retreat).
           - Try using Isaac Newton's action on the University of Oxford while it has 3 charges.
           - When using Chemotherapy offensively, make sure the enemy is either at full health or is low enough to be killed by the damage.`,
}

export default HarshMedicine

import DeckObject from '../structs/DeckObject'