const HarshMedicine: DeckObject = {
    id:  'HarshMedicine',
    name: 'Harsh Medicine',
    class: 'Learning',
    leader: 'Hippocrates',
    passive: 'HippocraticOath',
    cards: [
        // 'UniversityOfOxford',
        // 'UniversityOfOxford',
        // 'VenetianPatentStatute',
        // 'VenetianPatentStatute',
        'AlexanderFleming',
        'AlexanderFleming',
        'IsaacNewton',
        'IsaacNewton',
        // 'LibraryOfAlexandria',
        // 'LibraryOfAlexandria',
        'Chemotherapy',
        'Chemotherapy',
        'HelenOfTroy',
        'HelenOfTroy',
        'AlfredNobel',
        'AlfredNobel',
        // 'ThomasBodley',
        // 'ThomasBodley',
        // 'Triage',
        // 'Triage',
        'EdwardTheBlackPrince',
        'EdwardTheBlackPrince',
        'NancyKerrigan',
        'NancyKerrigan',
        'HenryFord',
        'HenryFord',
        'Robespierre',
        'Robespierre',
        // 'JohnFKennedy',
        // 'JohnFKennedy',
        'RansomEOlds',
        'RansomEOlds',
        'ErasmusExchange',
        'ErasmusExchange',
        'JRobertOppenheimer',
        'JRobertOppenheimer',
        'PrimaryEducation',
        'PrimaryEducation',
        'MonasticRetreat',
        'MonasticRetreat',
        'Dolly',
        'Dolly',
    ]
}

export default HarshMedicine

import DeckObject from '../structs/DeckObject'