const CitizenDeck: DeckObject = {
  id: 'CitizenDeck',
  name: 'Citizen Deck',
  leader: 'NapoleonBonaparte',
  passive: 'TulipMania',
  cards: [
    // 'Footman',
    // 'Footman',
    // 'Lictor',
    // 'Lictor',
    // 'Fireburst',
    // 'Fireburst',
    // 'BeveridgeReport',
    // 'BeveridgeReport',
    // 'CitizenAcademy',
    // 'CitizenAcademy',
    // 'PrinceTimothy',
    // 'PrinceTimothy',
    // 'CombatTraining',
    // 'CombatTraining',
    'NapalmStrike',
    'NapalmStrike',
    'Archimedes',
    'Archimedes',
    'TechEntrepreneur',
    'TechEntrepreneur',
    // 'Orpheus',
    // 'Orpheus',
    // 'JohnTheBaptist',
    // 'JohnTheBaptist',
    'Spartacus',
    'Spartacus',
    'Slave',
    'Slave',
    // 'JohannesGutenberg',
    // 'JohannesGutenberg',
    // 'MelvilDewey',
    // 'MelvilDewey',
    // 'NikolaTesla',
    // 'NikolaTesla',
    // 'Konigstiger',
    // 'Konigstiger',
  ]
}

export default CitizenDeck

import DeckObject from '../structs/DeckObject'