const CitizenDeck: DeckObject = {
  id: 'CitizenDeck',
  name: 'Citizen Deck',
  // leader: 'DavidHume',
  leader: 'NapoleonBonaparte',
  passive: 'TulipMania',
  // passive: 'ThrillOfDiscovery',
  cards: [
    'Footman',
    'Footman',
    'Lictor',
    'Lictor',
    // 'Fireburst',
    // 'Fireburst',
    'BeveridgeReport',
    'BeveridgeReport',
    'TwelveTables',
    'TwelveTables',
    'VladimirLenin',
    'VladimirLenin',
    'JamesMadison',
    'JamesMadison',
    // 'NapalmStrike',
    // 'NapalmStrike',
    // 'TechEntrepreneur',
    // 'TechEntrepreneur',
    // 'Orpheus',
    // 'Orpheus',
    // 'JohnTheBaptist',
    // 'JohnTheBaptist',
    'FrenchRevolution',
    'FrenchRevolution',
    'StatueOfLiberty',
    'StatueOfLiberty',
    'Collectivisation',
    'Collectivisation',
    // 'SpartacusGladiator',
    // 'SpartacusGladiator',
    // 'Slave',
    // 'Slave',
    // 'Archimedes',
    // 'Archimedes',
    // 'JohannesGutenberg',
    // 'JohannesGutenberg',
    // 'MelvilDewey',
    // 'MelvilDewey',
    // 'NikolaTesla',
    // 'NikolaTesla',
    // 'Konigstiger',
    // 'Konigstiger',
    // 'UniversityOfOxford',
    // 'UniversityOfOxford',
    // 'M1Abrams',
    // 'M1Abrams',
    // 'AlexanderFleming',
    // 'AlexanderFleming',
    // 'Dolly',
    // 'Dolly',
    // 'Sputnik',
    // 'Sputnik',
  ]
}

export default CitizenDeck

import DeckObject from '../structs/DeckObject'