const MassMobilisation: DeckObject = {
  id: 'MassMobilisation',
  name: 'Mass Mobilisation',
  class: 'The People',
  leader: 'NapoleonBonaparte',
  passive: 'GrandeArmee',
  cards: [
    'TwelveTables',
    'TwelveTables',
    'VladimirLenin',
    'VladimirLenin',
    'JamesMadison',
    'JamesMadison',
    'FrenchRevolution',
    'FrenchRevolution',
    'StatueOfLiberty',
    'StatueOfLiberty',
    'Collectivisation',
    'Collectivisation',
    'TupacShakur',
    'TupacShakur',
    'StormingOfTheBastille',
    'StormingOfTheBastille',
    'Robespierre',
    'Robespierre',
    'SaintJust',
    'SaintJust',
    'Cleon',
    'Cleon',
    'SubprimeBorrower',
    'SubprimeBorrower',
    'HelenOfTroy',
    'HelenOfTroy',
    // 'M1Abrams',
    // 'M1Abrams',
    'SamuelColt',
    'SamuelColt',
    'BostonTeaParty',
    'BostonTeaParty',
  ]
}

export default MassMobilisation

import DeckObject from '../structs/DeckObject'