const OrcDeck: DeckObject = {
  id: 'OrcDeck',
  name: 'Orc Deck',
  class: 'Empire',
  leader: 'OrkusTheOrkest',
  passive: 'SingleMindedFury',
  cards: [
    'JuniorOrc',
    'JuniorOrc',
    'SavageWolf',
    'SavageWolf',
    'Orcissimus',
    'Orcissimus',
    'Consume',
    'Consume',
    'ClubOfLooting',
    'ClubOfLooting',
    'CorporalMotivation',
    'CorporalMotivation',
    'BattleOfSuiyang',
    'BattleOfSuiyang',
    'SuicideBomber',
    'SuicideBomber',
    'BodyDouble',
    'BodyDouble',
    'WallLabourer',
    'WallLabourer',
    'DivideAndConquer',
    'DivideAndConquer',
    'JohnFKennedy',
    'JohnFKennedy',
    'JohnTheBaptist',
    'JohnTheBaptist',
    'Vaporise',
    'Vaporise',
  ],
}

export default OrcDeck

import DeckObject from '../structs/DeckObject'