const Supercontango: DeckObject = {
    id: 'Supercontango',
    name: 'Super-contango!',
    class: 'Economy',
    leader: 'CosimoDeMedici',
    passive: 'EconomiesOfScale',
    cards: [
        'Konigstiger',
        'Konigstiger',
        // 'M1Abrams',
        // 'M1Abrams',
        // 'TechEntrepreneur',
        // 'TechEntrepreneur',
        // 'BeveridgeReport',
        // 'BeveridgeReport',
        'MarketManipulation',
        'MarketManipulation',
        'NewDeal',
        'NewDeal',
        // 'GeorgeMarshall',
        // 'GeorgeMarshall',
        // 'CDOTrader',
        // 'CDOTrader',
        // 'EdwardTheBlackPrince',
        // 'EdwardTheBlackPrince',
        'IndustrialRevolution',
        'IndustrialRevolution',
        'IsaacLeMaire',
        'IsaacLeMaire',
        'Tractor',
        'Tractor',
        // 'AneurinBevan',
        // 'AneurinBevan',
        // 'Theodora',
        // 'Theodora',
        // 'SubprimeBorrower',
        // 'SubprimeBorrower',
        'NikaHooligan',
        'NikaHooligan',
        'CharlesPonzi',
        'CharlesPonzi',
        'HenryFord',
        'HenryFord',
        // 'FidelCastro',
        // 'FidelCastro',
        'Supercontango',
        'Supercontango',
        'DeficitSpending',
        'DeficitSpending',
        // 'Galleon',
        // 'Galleon',
        'MuiTsai',
        'MuiTsai',
        'Helot',
        'Helot',
        // 'HelenOfTroy',
        // 'HelenOfTroy',
        // 'Atalanta',
        // 'Atalanta',
        'Banker',
        'Banker',
        'RichardNixon',
        'RichardNixon',
    ],
    description: `Recreate the historic negative oil pricing incident of April 2020, in this tricky combo deck. A unique opportunity for free followers awaits - provided you can find somewhere to put them.`,
    tips: `- Use your leader technique whenever you can afford to. If you have Henry Ford in play, it means adding a stack of Economies of Scale for free.
           - Try to have as many cards in your hand as possible when you play Richard Nixon. Remember, he can discount Coins too.
           - Choose the order of your cards carefully, to make the most of Economies of Scale.
           - An Investment Banker is a good way to finish a Super-contango play.`,
}

export default Supercontango

import DeckObject from '../structs/DeckObject'