const Supercontango: DeckObject = {
    id: 'Supercontango',
    name: 'Super-contango!',
    class: 'Economy',
    leader: 'CosimoDeMedici',
    passive: 'EconomiesOfScale',
    cards: [
        // 'Konigstiger',
        // 'Konigstiger',
        // 'M1Abrams',
        // 'M1Abrams',
        // 'TechEntrepreneur',
        // 'TechEntrepreneur',
        // 'BeveridgeReport',
        // 'BeveridgeReport',
        // 'MarketManipulation',
        // 'MarketManipulation',
        'NewDeal',
        'NewDeal',
        // 'GeorgeMarshall',
        // 'GeorgeMarshall',
        // 'CDOTrader',
        // 'CDOTrader',
        // 'EdwardTheBlackPrince',
        // 'EdwardTheBlackPrince',
        // 'IndustrialRevolution',
        // 'IndustrialRevolution',
        'IsaacLeMaire',
        'IsaacLeMaire',
        'Tractor',
        'Tractor',
        // 'AneurinBevan',
        // 'AneurinBevan',
        'Theodora',
        'Theodora',
        'SubprimeBorrower',
        'SubprimeBorrower',
        'CharlesPonzi',
        'CharlesPonzi',
        'HenryFord',
        'HenryFord',
        // 'FidelCastro',
        // 'FidelCastro',
        'Supercontango',
        'Supercontango',
        'DeficitSpending',
        'DeficitSpending',
        // 'Galleon',
        // 'Galleon',
        'MuiTsai',
        'MuiTsai',
        'Helot',
        'Helot',
        'HelenOfTroy',
        'HelenOfTroy',
        'Atalanta',
        'Atalanta',
        'Investor',
        'Investor',
        'RichardNixon',
        'RichardNixon',
    ]
}

export default Supercontango

import DeckObject from '../structs/DeckObject'