const ThinkThank: DeckObject = {
    id: 'ThinkTank',
    name: 'Think Tank',
    class: 'Learning',
    leader: 'DavidHume',
    passive: 'ThrillOfDiscovery',
    cards: [
        'Archimedes',
        'Archimedes',
        'JohannesGutenberg',
        'JohannesGutenberg',
        'MelvilDewey',
        'MelvilDewey',
        'NikolaTesla',
        'NikolaTesla',
        'Konigstiger',
        'Konigstiger',
        'M1Abrams',
        'M1Abrams',
        'UniversityOfOxford',
        'UniversityOfOxford',
        'AlexanderFleming',
        'AlexanderFleming',
        'Dolly',
        'Dolly',
        // 'AugusteEscoffier',
        // 'AugusteEscoffier',
        'IsaacNewton',
        'IsaacNewton',
        'Chemotherapy',
        'Chemotherapy',
        'HelenOfTroy',
        'HelenOfTroy',
        'VenetianPatentStatute',
        'VenetianPatentStatute',
        'MarySomerville',
        'MarySomerville',
        'Type42Destroyer',
        'Type42Destroyer',
    ]
}

export default ThinkThank

import DeckObject from '../structs/DeckObject'