const TulipMAD: DeckObject = {
    id: 'TulipMAD',
    name: 'Tulip MAD',
    class: 'Economy',
    leader: 'FranklinRoosevelt',
    passive: 'TulipMania',
    cards: [
        'Konigstiger',
        'Konigstiger',
        'M1Abrams',
        'M1Abrams',
        'TechEntrepreneur',
        'TechEntrepreneur',
        'BeveridgeReport',
        'BeveridgeReport',
        'MarketManipulation',
        'MarketManipulation',
        'NewDeal',
        'NewDeal',
        'GeorgeMarshall',
        'GeorgeMarshall',
        'CDOTrader',
        'CDOTrader',
        // 'EdwardTheBlackPrince',
        // 'EdwardTheBlackPrince',
        // 'IndustrialRevolution',
        // 'IndustrialRevolution',
        'Investor',
        'Investor',
        'AneurinBevan',
        'AneurinBevan',
        // 'SubprimeBorrower',
        // 'SubprimeBorrower',
        'CharlesPonzi',
        'CharlesPonzi',
        'HenryFord',
        'HenryFord',
        'FidelCastro',
        'FidelCastro',
        'DeficitSpending',
        'DeficitSpending',
        'Galleon',
        'Galleon',
    ]
}

export default TulipMAD

import DeckObject from '../structs/DeckObject'