const TulipMAD: DeckObject = {
    id: 'TulipMAD',
    name: 'Tulip MAD',
    class: 'Economy',
    leader: 'FranklinRoosevelt',
    passive: 'TulipMania',
    cards: [
        'Konigstiger',
        'Konigstiger',
        'M1Abrams',
        'M1Abrams',
        'TechEntrepreneur',
        'TechEntrepreneur',
        'BeveridgeReport',
        'BeveridgeReport',
        'MarketManipulation',
        'MarketManipulation',
        'NewDeal',
        'NewDeal',
        // 'GeorgeMarshall',
        // 'GeorgeMarshall',
        'CDOTrader',
        'CDOTrader',
        'Tractor',
        'Tractor',
        // 'EdwardTheBlackPrince',
        // 'EdwardTheBlackPrince',
        // 'IndustrialRevolution',
        // 'IndustrialRevolution',
        'Banker',
        'Banker',
        'AneurinBevan',
        'AneurinBevan',
        // 'SubprimeBorrower',
        // 'SubprimeBorrower',
        'CharlesPonzi',
        'CharlesPonzi',
        'HenryFord',
        'HenryFord',
        'FidelCastro',
        'FidelCastro',
        'DeficitSpending',
        'DeficitSpending',
        'Galleon',
        'Galleon',
    ],
    description: `Lead America out of the Great Depression in this value-oriented deck. Overwhelm your opponent through efficent trades, or take advantage of your Ethos to survive a nuclear exchange.`,
    tips: `- CDO Trader is a good target for your buffs.
           - Henry Ford is very valuable - prioritise keeping him alive.
           - Market Manipulation and the Beveridge Report synergise well with Retail Bankers.`,
}

export default TulipMAD

import DeckObject from '../structs/DeckObject'